"""cart and cart item

Revision ID: de3f82b54a3c
Revises: 8f743d403e0a
Create Date: 2023-11-26 00:18:02.814009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de3f82b54a3c"
down_revision: Union[str, None] = "8f743d403e0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date_created_utc", sa.DateTime(), nullable=True),
        sa.Column("date_updated_utc", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "cart_items",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column("is_purchased", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date_created_utc", sa.DateTime(), nullable=True),
        sa.Column("date_updated_utc", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["carts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("products", sa.Column("tracker", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "tracker")
    op.drop_table("cart_items")
    op.drop_table("carts")
    # ### end Alembic commands ###
